// Doodlebrook Schools: a made-up school used to demo the website and portal.
export const school = {
  name: "Doodlebrook Schools",
  shortName: "Doodlebrook",
  kind: "Creche, Nursery & Primary · Day school",
  tagline: "Every child is a masterpiece",
  motto: "Imagine, Create, Achieve",
  mission: "To give every child the space, skills and confidence to imagine boldly and learn joyfully.",
  mascot: "Pip",
  approvals: ["Government approved"],
  logo: "/images/logo.svg",
  // Demo accounts, ID numbers and receipt numbers.
  demoDomain: "doodlebrook.test",
  demoPassword: "doodlebrook",
  admissionPrefix: "DBS",
  receiptPrefix: "DB",
  address: "4 Rainbow Crescent, Wuse 2, Abuja",
  shortAddress: "4 Rainbow Crescent, Wuse 2, Abuja",
  phones: ["0800 000 3301", "0800 000 3302"],
  email: "hello@doodlebrook-schools.example",
  currentTerm: "First Term",
  currentSession: "2026/2027",
  entranceExams: ["2026-07-11", "2026-08-01", "2026-08-22", "2026-09-05"],
  highlights: [
    { label: "Creche to Primary 6", value: "🧸", text: "One happy campus from first steps to first exams" },
    { label: "Small classes", value: "✏️", text: "No more than 20 little artists in a class" },
    { label: "Art every day", value: "🖍️", text: "Drawing, making and music woven into lessons" },
    { label: "Govt. approved", value: "✅", text: "A government approved day school" },
  ],
};
