// Owlberry International School: a fictional school used to demo this website and portal.
export const school = {
  name: "Owlberry International School",
  shortName: "Owlberry",
  kind: "Nursery, Primary & Secondary · Day & Boarding",
  tagline: "Where little explorers grow wise",
  motto: "Grow, Explore, Shine",
  mission: "To grow wise, caring and confident children, rooted in strong values and ready for the world.",
  mascot: "Professor Hoot",
  approvals: ["Government approved", "Nursery to Secondary", "Day & Boarding"],
  logo: "/images/logo.svg",
  // Demo accounts, ID numbers and receipt numbers.
  demoDomain: "owlberry.test",
  demoPassword: "owlberry",
  admissionPrefix: "OIS",
  receiptPrefix: "OB",
  address: "21 Orchard Avenue, Bodija, Ibadan, Oyo State",
  shortAddress: "21 Orchard Avenue, Bodija, Ibadan",
  phones: ["0800 000 2201", "0800 000 2202"],
  email: "hello@owlberry-school.example",
  currentTerm: "First Term",
  currentSession: "2026/2027",
  entranceExams: ["2026-07-11", "2026-08-01", "2026-08-22", "2026-09-05"],
  highlights: [
    { label: "Treehouse classrooms", value: "🌳", text: "Bright, leafy rooms where curiosity climbs high", fruit: "mango" },
    { label: "Explorer clubs", value: "🧭", text: "Nature trails, robotics, drama and drumming", fruit: "berry" },
    { label: "Cosy boarding", value: "🛏️", text: "Caring house parents and a home-from-home nest", fruit: "lime" },
    { label: "Wise & kind", value: "🦉", text: "Values-first learning with Professor Hoot", fruit: "plum" },
  ],
};
