// Novaridge Academy: a made-up school used to demo this website and portal.
export const school = {
  name: "Novaridge Academy",
  shortName: "Novaridge",
  kind: "Nursery & Primary · Day school",
  tagline: "Reach for the stars, one lesson at a time",
  motto: "Curious minds, bright futures",
  mission: "To nurture brave, curious and kind young explorers who love learning.",
  approvals: ["Government approved", "Nursery & Primary", "Small classes"],
  logo: "/images/logo.svg",
  mascot: "Nova",
  // Demo accounts, ID numbers and receipt numbers.
  demoDomain: "novaridge.test",
  demoPassword: "novaridge",
  admissionPrefix: "NRA",
  receiptPrefix: "NR",
  address: "7 Comet Close, Lekki Phase 1, Lagos",
  shortAddress: "7 Comet Close, Lekki Phase 1, Lagos",
  phones: ["0800 000 1101", "0800 000 1102"],
  email: "hello@novaridge-academy.example",
  currentTerm: "First Term",
  currentSession: "2026/2027",
  entranceExams: ["2026-07-11", "2026-08-01", "2026-08-22", "2026-09-05"],
  highlights: [
    { label: "Ages 1 to 11", value: "🚀", text: "Creche, nursery and primary under one sky" },
    { label: "Small crews", value: "👩‍🚀", text: "No more than 20 explorers in a class" },
    { label: "Hands-on STEM", value: "🔭", text: "A science lab, a garden and a mini observatory" },
    { label: "Kind hearts", value: "💫", text: "Kindness and courage taught in every lesson" },
  ],
};
